# Generated by Django 5.0.7 on 2024-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=60)),
                ('views_count', models.IntegerField()),
                ('position', models.IntegerField(unique=True)),
            ],
        ),
    ]
