# Generated by Django 5.0.7 on 2024-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='position',
            field=models.IntegerField(),
        ),
    ]
